version: '3.8'

volumes:
    pgdata:
        driver: local
services:
    nginx:
        restart: always
        image: nginx:latest
        expose:
            - 8080
        ports:
            - "80:8080"
        volumes:
            - ./static:/srv/www/library/static
            - ./media:/srv/www/library/media
            - ./logs:/srv/www/library/logs
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - python
    python:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/srv/www/library
        expose:
            - 8000
        ports:
            - 8000:8000
        command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn -c gunicorn.py library.wsgi"
        depends_on:
            - postgres
        secrets:
            - postgres_user_name
            - postgres_password
    redis:
        image: "redis:alpine"
    celery:
        build: .
        command: celery -A library worker -l info
        volumes:
            - .:/srv/celery
        depends_on:
            - redis
            - python
    celery-beat:
        build: .
        command: celery -A library beat -l info
        volumes:
            - .:/srv/celery-beat
        depends_on:
            - redis
            - python
    postgres:
        image: postgres:12.3
        environment:
            - POSTGRES_USER_FILE=/run/secrets/postgres_user_name
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data
        secrets:
            - postgres_user_name
            - postgres_password
secrets:
    postgres_user_name:
        file: secrets/postgres_user_name.txt
    postgres_password:
        file: secrets/postgres_password.txt